# Generated by Django 3.1.1 on 2021-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(default='foo', max_length=100)),
                ('customer_lname', models.CharField(default='foo', max_length=100)),
                ('customer_address', models.CharField(default='foo', max_length=100)),
                ('customer_id', models.CharField(default='foo', max_length=100)),
                ('customer_phone', models.CharField(default='foo', max_length=12)),
                ('customer_email', models.CharField(default='foo', max_length=100)),
            ],
        ),
    ]
