# Generated by Django 3.1.1 on 2021-01-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractclassforProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='foo', max_length=100)),
                ('desc', models.CharField(default='foo', max_length=100)),
                ('upload', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('abstractclassforproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.abstractclassforproduct')),
                ('category_id', models.CharField(default='foo', max_length=100)),
            ],
            bases=('Products.abstractclassforproduct',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('abstractclassforproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.abstractclassforproduct')),
                ('product_id', models.CharField(default='foo', max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            bases=('Products.abstractclassforproduct',),
        ),
    ]
